### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Games4k** [fix8software/Stonewall#3]
```
[13:39:25 INFO] [velocityqueue]: Loaded VelocityQueue!
[13:39:25 INFO]: Loaded plugin velocityqueue 1.0-SNAPSHOT by Epix
[13:39:25 INFO]: Loaded 5 plugins
[13:39:25 INFO]:         __    
[13:39:25 INFO]:   |    |__)   LuckPerms v5.1.87
[13:39:25 INFO]:   |___ |      Running on Velocity - Velocity
[13:39:25 INFO]:
[13:39:25 INFO] [luckperms]: Loading configuration...
[13:39:25 INFO] [luckperms]: Loading storage provider... [H2]
[13:39:25 INFO] [luckperms]: Loading internal permission managers...
[13:39:25 INFO] [luckperms]: Performing initial data load...
[13:39:25 INFO] [luckperms]: Successfully enabled. (took 723ms)
[13:39:25 INFO] [maintenance]: Plugin by KennyTV
[13:39:25 ERROR]: Aug 13, 2020 1:39:25 PM skinsrestorer.shared.utils.SRLogger logAlways
[13:39:25 ERROR]: INFO: [SkinsRestorer] Enabling SkinsRestorer v13.8.2
[13:39:26 INFO]: [SkinsRestorer] Permissions.NewPermissions is missing in config.yml! Using default value.
[13:39:26 INFO]: [SkinsRestorer] ----------------------------------------------
[13:39:26 INFO]: [SkinsRestorer]     +===============+
[13:39:26 INFO]: [SkinsRestorer]     | SkinsRestorer |
[13:39:26 INFO]: [SkinsRestorer]     +===============+
[13:39:26 INFO]: [SkinsRestorer] ----------------------------------------------
[13:39:26 INFO]: [SkinsRestorer]     Current version: 13.8.2
[13:39:26 INFO]: [SkinsRestorer]     This is the latest version!
[13:39:26 INFO]: [SkinsRestorer] ----------------------------------------------
[13:39:26 ERROR]: Aug 13, 2020 1:39:26 PM skinsrestorer.shared.utils.SRLogger logAlways
[13:39:26 ERROR]: INFO: [SkinsRestorer] Enabled SkinsRestorer v13.8.2
[13:39:26 ERROR]: Some errors occurred whilst posting event ProxyInitializeEvent.
[13:39:26 ERROR]: #1: 

java.lang.NoClassDefFoundError: me/lucko/luckperms/LuckPerms
        at org.smplite.velocityqueue.Queue.<init>(Queue.java:44) ~[?:?]
        at org.smplite.velocityqueue.VelocityQueue.onProxyInitialize(VelocityQueue.java:40) ~[?:?]
        at net.kyori.event.asm.generated.e025a8f915.VelocityQueue-onProxyInitialize-ProxyInitializeEvent-5.invoke(Unknown Source) ~[?:?]
        at net.kyori.event.method.SimpleMethodSubscriptionAdapter$MethodEventSubscriber.invoke(SimpleMethodSubscriptionAdapter.java:148) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at net.kyori.event.SimpleEventBus.post(SimpleEventBus.java:107) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.fireEvent(VelocityEventManager.java:136) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at com.velocitypowered.proxy.plugin.VelocityEventManager.lambda$fire$0(VelocityEventManager.java:117) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: me.lucko.luckperms.LuckPerms
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:66) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:43) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 10 more

```

Seems like it thinks Luckperms is not installed even tho it is, or Luckperms changed API class name?

**Comment by naphthasl** [comment]
Probably some change made to Luckperms. We uh... haven't maintained this since 1.14, since the server this was supposed to be used for never actually ended up needing it.

Not sure if we really want to go through the effort of updating it for new versions of LuckPerms, but it shouldn't be **too** hard so we might look into it. How badly do you need this fixed?

**Comment by Games4k** [comment]
Well, I was able to fix it, just implemented a new LuckPerms API, added dependency inside @Plugin, and the plugin worked. HOWEVER, there is a much bigger issue now that I do not know how to fix. StoneWall is completely misfunctioning, on 1.8.8, 1.15.2, and 1.16.1. This error is thrown:

![Screen Shot 2020-08-13 at 3 19 31 PM](https://user-images.githubusercontent.com/29690431/90139463-b58dbb00-dd78-11ea-9ac1-d08317007e36.png)

I'd totally like to use such a plugin like this. It's highly interesting and would be a great addon for those bots that pass my antibot to be stopped in the queue and not make any damage to the rest of the server. Additionally, I'm planing to open my new server soon, so a queue system would be great. I mean, it's not really of the utmost importance to me, but I'd really like to have such plugin on my server :) 

If you are not able to solve it then I will probably try using https://github.com/TyphoonMC/TyphoonLimbo as the Queue server ;)

**Comment by Games4k** [comment]
And sadly, I've just tagged some random guy 😂

**Comment by Games4k** [comment]
Btw, this project is probably underrated due to being only compatible with Velocity. I think making something like this (but probably more advanced), but BungeeCord would be able highly popular on SpigotMC, and you may be able to publish it even as a premium plugin and earn lots of money. (however, in that case, please leave Velocity support as I prefer it over Bungee 😂)

**Comment by naphthasl** [comment]
What happens when you try to connect directly to the stonewall.py server through the client instead of through velocity? Anything different about it?

**Comment by Games4k** [comment]
It's the same

**Comment by Games4k** [comment]
```
[15:10:39 INFO]: [server connection] OfficialSource -> lobby has disconnected
[15:10:39 ERROR]: [connected player] OfficialSource (/89.216.134.157:53667): unable to connect to server lobby
java.io.IOException: Unexpectedly disconnected from remote server
        at com.velocitypowered.proxy.connection.backend.TransitionSessionHandler.disconnected(TransitionSessionHandler.java:187) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at com.velocitypowered.proxy.connection.MinecraftConnection.channelInactive(MinecraftConnection.java:94) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:1.1.0-SNAPSHOT (git-5cceebdf-b211)]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Here is the error from the Velocity

**Comment by naphthasl** [comment]
Alright, I think the issue in that case is that different Minecraft versions require different formatting for the data sent to the client on join - if this is the case, the problem is going to be much more difficult to solve, because we'd need some standard way to detect the client version and then send a completely different format for each version of the client. This wouldn't be so bad if Mojang actually documented literally anything instead of depending on the community to do it for them [poorly].

Does Velocity have any plugin similar to ViaVersion? I'm thinking maybe you could set up another proxy or something that connects to the queue server using the 1.14.4 protocol version and then automatically does all of the translation stuff for other versions. Does that exist?
